name: CI test
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Self test
        uses: luisrayas3/join-job-results@master
        with:
          results: '["success", "fail"]'
      # TODO: Test a non-success case

  # TODO: black-ify
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: "3.7"

      - uses: actions/checkout@v1

      - name: Lint
        run: |
          pip install flake8
          flake8 main.py
